site_name: OpenBouffalo Wiki
theme: material
nav:
  - Home: index.md
  - Common:
    - 'Boot Header': 'common/boot-header.md'
  - Chips:
    - 'BL70X Series':
      - 'General Information': 'chips/bl70x/info.md'
      - eFuse: 'chips/bl70x/efuse.md'
      - Errata: 'chips/bl70x/errata.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences